// ssr/angular-ssr/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { ListComponent } from '../components/list.component';

// Services
import { CitiesService } from '../services/cities.service';
import { RenderDateService } from '../services/renderDate.service';

// Types
import { Cities } from '../types';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, ListComponent],
  template: `
    <main>
      <p class="bg-black text-white font-mono text-center py-2 text-sm">
        Rendered at {{ renderTime }} by Angular
      </p>
      <p
        class="max-w-3xl rounded-3xl mt-6 px-8 py-6 bg-neutral-100 font-mono mx-auto"
      >
        {{ license }}
      </p>
      <list-component [cities]="cities" />
      <p
        class="max-w-3xl rounded-3xl mt-6 px-8 py-6 bg-yellow-200/50 shadow-yellow-200/10 shadow-xl text-xs border border-yellow-200 font-mono mx-auto"
      >
        All the ciredit for the provided data goes to {{ credit }}
      </p>
      <router-outlet></router-outlet>
    </main>
  `,
  providers: [CitiesService, RenderDateService],
})
export class AppComponent {
  CitiesService = inject(CitiesService);
  RenderDateService = inject(RenderDateService);

  // items
  renderTime = '';
  cities: Cities = [];
  credit = '';
  license = '';

  constructor(
    private citiesService: CitiesService,
    private renderDateService: RenderDateService
  ) {}

  ngOnInit() {
    this.citiesService.getData().subscribe(({ cities, credit, license }) => {
      this.cities = cities;
      this.credit = credit;
      this.license = license;
    });

    const { renderedAt } = this.renderDateService.get();
    this.renderTime = renderedAt;
  }
}

<main class="my-12">
  <h1 class="text-3xl text-center uppercase">Angular SSR</h1>
</main>

<router-outlet></router-outlet>

// ssr/next-ssr/src/app/page.tsx
// Types
import { Cities } from "@/type";

// Components
import List from "@/components/list";

// Forcing the page to be fully dynamic
export const dynamic = "force-dynamic";

// Data Fetching
async function getData() {
  const date = new Date();
  const renderTime = `${date.getUTCHours().toString().padStart(2, "0")}:${date
    .getUTCMinutes()
    .toString()
    .padStart(2, "0")}:${date
    .getUTCSeconds()
    .toString()
    .padStart(2, "0")}:${date
    .getUTCMilliseconds()
    .toString()
    .padStart(2, "0")}`;

  const { cities, credit, license } = (await fetch("http://localhost:3090", {
    cache: "no-store",
  }).then((data) => data.json())) as {
    cities: Cities;
    license: string;
    credit: string;
  };

  return { renderTime, cities, credit, license };
}

export default async function Home() {
  const { renderTime, cities, credit, license } = await getData();

  return (
    <main>
      <p className="bg-black text-white font-mono text-center py-2 text-sm">
        Rendered at {renderTime}
      </p>
      <p className="max-w-3xl rounded-3xl mt-6 px-8 py-6 bg-neutral-100 font-mono mx-auto">
        {license}
      </p>
      <List cities={cities} />
      <p className="max-w-3xl rounded-3xl mt-6 px-8 py-6 bg-yellow-200/50 shadow-yellow-200/10 shadow-xl text-xs border border-yellow-200 font-mono mx-auto">
        All the ciredit for the provided data goes to {credit}
      </p>
    </main>
  );
}
